import React from "react";
import { Card, CardContent } from "../components/ui/card";

export default function TermsPage() {
    return (
        <div className="space-y-6 p-4 md:p-6 max-w-3xl mx-auto">
            <h1 className="scaffold-heading">Terms of Service</h1>
            <Card>
                <CardContent className="p-6 space-y-4 text-sm text-muted-foreground">
                    <p>Last updated: 2026</p>
                    <h3 className="font-semibold text-eld-space-indigo dark:text-gray-200">Acceptance of Terms</h3>
                    <p>By using VAMS ELD, you agree to these terms of service. If you do not agree, do not use the service.</p>
                    <h3 className="font-semibold text-eld-space-indigo dark:text-gray-200">Use of Service</h3>
                    <p>VAMS ELD is provided for educational purposes to teachers at Valor Academy Middle School and Bright Star Schools. You agree to use the service only for lawful educational purposes.</p>
                    <h3 className="font-semibold text-eld-space-indigo dark:text-gray-200">User Accounts</h3>
                    <p>You are responsible for maintaining the confidentiality of your account credentials. Only Bright Star Schools email addresses are permitted to create accounts.</p>
                    <h3 className="font-semibold text-eld-space-indigo dark:text-gray-200">AI-Generated Content</h3>
                    <p>Scaffolded assignments are generated by AI and should be reviewed by the teacher before use. The developers are not responsible for the accuracy or appropriateness of AI-generated content.</p>
                    <h3 className="font-semibold text-eld-space-indigo dark:text-gray-200">Limitation of Liability</h3>
                    <p>VAMS ELD is provided "as is" without warranty of any kind. The developers shall not be liable for any damages arising from the use of this service.</p>
                </CardContent>
            </Card>
        </div>
    );
}